load("@aspect_rules_py//py:defs.bzl", "py_binary", "py_library")

py_binary(
    name = "lock",
    srcs = ["lock.py"],
    visibility = ["//:__subpackages__"],
)

py_library(
    name = "lock_library",
    srcs = ["lock.py"],
    visibility = ["//:__subpackages__"],
)
